"use client"
import './globals.css';
import { Auth0Provider } from '@auth0/auth0-react';


export const metadata = {
  title: 'Realtime Drawing App ',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<Auth0Provider
    domain="dev-n1bma7b2joy3x4as.us.auth0.com"
    clientId="a9OumnnckR7MIamqt4exyay2mcBNppoq"
    authorizationParams={{
      redirect_uri: window.location.origin
    }} 
  >
    <body suppressHydrationWarning >{children}</body>
  </Auth0Provider>,      
    </html>
  )
}


















